; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\abans\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
